changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: New features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Dependencies and maintenance
      labels:
        - dependencies
        - maintenance
    - title: Other changes
      labels:
        - "*"
