import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { createInterface } from "node:readline/promises";
import {
  classifyPublicAddress,
  displayHttpAddress,
  type DeploymentMode,
  type PublicAddress,
} from "./deployment.ts";
import { promptAndHashPassword, validatePanelUsername } from "./password.ts";

export type InitializationMode = "production" | "test";

interface InitializationOptions {
  home: string;
  mode: InitializationMode;
  dataDirectoryName?: string;
  username?: string;
  publicAddress?: string;
  acceptInsecureHttp?: boolean;
}

export interface InitializationResult {
  configPath: string;
  dataDir: string;
  username: string;
  publicAddress: string;
  deploymentMode: DeploymentMode;
  listenHost: string;
  port: number;
}

async function textPrompt(label: string): Promise<string> {
  if (!process.stdin.isTTY || !process.stdout.isTTY) {
    throw new Error("An interactive terminal is required for first-time setup");
  }
  const prompt = createInterface({ input: process.stdin, output: process.stdout });
  try {
    return await prompt.question(label);
  } finally {
    prompt.close();
  }
}

async function requireInsecureHttpConfirmation(address: string): Promise<void> {
  console.warn("\nWARNING: Direct HTTP does not encrypt passwords, session cookies, or panel traffic.");
  console.warn("Use this only when HTTPS is genuinely unavailable and protect access with a firewall or VPN.");
  const answer = (await textPrompt(`Expose the panel at http://${address}:3001 anyway? [y/N]: `))
    .trim()
    .toLowerCase();
  if (answer !== "y" && answer !== "yes") {
    throw new Error("Direct HTTP setup cancelled");
  }
}

export async function initializeConfiguration({
  home,
  mode,
  dataDirectoryName = "panel-data",
  username: suppliedUsername,
  publicAddress: suppliedAddress,
  acceptInsecureHttp = false,
}: InitializationOptions): Promise<InitializationResult> {
  const dataDir = path.join(home, dataDirectoryName);
  const configPath = path.join(dataDir, "config.toml");
  if (await Bun.file(configPath).exists()) {
    throw new Error(`Refusing to replace existing configuration: ${configPath}`);
  }

  console.log(
    mode === "test"
      ? "Initializing an isolated localhost test configuration."
      : "Initializing production configuration.",
  );
  const usernameInput = suppliedUsername ?? (await textPrompt("Administrator username [admin]: "));
  const username = usernameInput.trim() || "admin";
  validatePanelUsername(username);
  console.log(`Choose the password you will use to log in as '${username}'.`);
  const passwordHash = await promptAndHashPassword();
  const jwtSecret = new Uint8Array(32);
  crypto.getRandomValues(jwtSecret);
  const port = 3001;

  let address: PublicAddress;
  let deploymentMode: DeploymentMode;
  if (mode === "test") {
    address = {
      value: "127.0.0.1",
      kind: "ipv4",
      deploymentMode: "direct-http",
      listenHost: "127.0.0.1",
    };
    deploymentMode = "test";
  } else {
    const addressInput =
      suppliedAddress ?? (await textPrompt("Public DNS name or server IP address: "));
    address = classifyPublicAddress(addressInput);
    deploymentMode = address.deploymentMode;
    if (deploymentMode === "direct-http" && !acceptInsecureHttp) {
      await requireInsecureHttpConfirmation(address.value);
    }
  }

  const contents = `# Generated by Minecraft Server Panel. Keep this file private.\n${Bun.TOML.stringify({
    root_username: username,
    root_password_hash: passwordHash,
    jwt_secret: Buffer.from(jwtSecret).toString("hex"),
    public_address: address.value,
    deployment_mode: deploymentMode,
    listen_host: address.listenHost,
    port,
    secure_cookie: deploymentMode === "https",
    allow_insecure_http: deploymentMode === "direct-http",
    environment: mode === "test" ? "test" : "production",
    upload_max_bytes: 2_147_483_648,
  })}`;

  await mkdir(dataDir, { recursive: true, mode: 0o700 });
  await writeFile(configPath, contents, { encoding: "utf8", flag: "wx", mode: 0o600 });
  await Promise.all([
    mkdir(path.join(dataDir, "database"), { recursive: true }),
    mkdir(path.join(dataDir, "servers"), { recursive: true }),
  ]);
  console.log(`Created ${configPath}`);
  console.log(`Mutable data will be stored in ${dataDir}`);
  if (deploymentMode === "https") {
    console.log(`Public URL: https://${address.value}`);
    console.log("The app listens only on 127.0.0.1:3001; the release installer configures Caddy.");
  } else {
    console.log(`Open http://${displayHttpAddress(address, port)}`);
  }

  return {
    configPath,
    dataDir,
    username,
    publicAddress: address.value,
    deploymentMode,
    listenHost: address.listenHost,
    port,
  };
}
